# Generated by Django 2.1.7 on 2019-02-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='upload',
            new_name='file',
        ),
    ]
